name: lpdw_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  share_plus: ^9.0.0

  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  simple_barcode_scanner: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  retrofit_generator: ^8.1.0
  json_serializable: any

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - res/drawables/
    - res/fonts/
    - res/svg/

  fonts:
    - family: AppIcons
      fonts:
        - asset: res/fonts/app_icons.ttf